# Generated by Django 5.2.6 on 2025-10-31 23:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incid', models.CharField(max_length=255)),
                ('descripcion_incid', models.CharField(max_length=255)),
                ('estado_incid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidenteEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ocurrencia', models.DateField()),
                ('observaciones', models.CharField(max_length=255)),
                ('responsable_registro', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('CORREGIDO', 'Corregido')], default='ABIERTO', max_length=20)),
                ('id_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('id_incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidentes.incidente')),
            ],
        ),
        migrations.CreateModel(
            name='Descargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_descargo', models.DateTimeField(default=django.utils.timezone.now)),
                ('contenido_descargo', models.CharField(max_length=255)),
                ('ruta_archivo_descargo', models.FileField(blank=True, null=True, upload_to='descargos/')),
                ('estado', models.BooleanField(default=True)),
                ('id_incid_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargos', to='incidentes.incidenteempleado')),
            ],
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_resolucion', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('id_incid_empl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolucion', to='incidentes.incidenteempleado')),
            ],
        ),
    ]
