# Generated by Django 5.2.6 on 2025-11-01 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('incidentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='descargo',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.empleado'),
        ),
    ]
