# Generated by Django 5.2.6 on 2025-11-01 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('incidentes', '0002_descargo_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolucion',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.empleado'),
        ),
    ]
