# Generated by Django 5.2.6 on 2025-11-02 23:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0003_alter_resolucion_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolucion',
            name='id_incid_empl',
        ),
        migrations.AddField(
            model_name='incidenteempleado',
            name='grupo_incidente',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único para agrupar incidentes creados en la misma operación.'),
        ),
        migrations.AddField(
            model_name='resolucion',
            name='grupo_incidente',
            field=models.UUIDField(default=2525, help_text='El grupo de incidentes que esta resolución cierra.', unique=True),
            preserve_default=False,
        ),
    ]
