# Generated by Django 5.2.6 on 2025-11-13 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('incidentes', '0004_remove_resolucion_id_incid_empl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenteempleado',
            name='responsable_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_registrados', to='empleados.empleado'),
        ),
    ]
