# Generated by Django 5.2.6 on 2025-11-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0005_alter_incidenteempleado_responsable_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenteempleado',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='incidenteempleado',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
