# Generated by Django 5.2.6 on 2025-11-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0006_incidenteempleado_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenteempleado',
            name='grupo_anterior',
            field=models.UUIDField(blank=True, help_text='UUID del grupo de incidente que este nuevo grupo corrige.', null=True),
        ),
    ]
