# Generated by Django 5.2.6 on 2025-10-01 00:01

import django.db.models.deletion
import empleados.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_doc', models.CharField(max_length=100)),
                ('estado_doc', models.BooleanField(default=True)),
                ('obligatorio', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.IntegerField(unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1)),
                ('estado_civil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo')], default='Soltero', max_length=20)),
                ('fecha_nacimiento', models.DateField(validators=[empleados.models.validar_mayor_18])),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido'), ('Licencia', 'Licencia')], default='Activo', max_length=20)),
                ('ruta_foto', models.ImageField(blank=True, null=True, upload_to='empleados/fotos/')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Legajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_leg', models.CharField(max_length=50)),
                ('fecha_creacion_leg', models.DateField(auto_now_add=True)),
                ('nro_leg', models.IntegerField(unique=True)),
                ('fecha_modificacion_leg', models.DateField(auto_now=True)),
                ('id_empl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legajo', to='empleados.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_archivo', models.FileField(upload_to='legajos/documentos/')),
                ('fecha_hora_subida', models.DateTimeField(auto_now_add=True)),
                ('descripcion_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_doc', models.BooleanField(default=True)),
                ('id_leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.legajo')),
                ('id_requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.requisitodocumento')),
            ],
        ),
    ]
