# Generated by Django 5.2.6 on 2025-11-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='password_cambiada',
            field=models.BooleanField(default=False),
        ),
    ]
