"""
Django settings for api_nuevas_energias project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pu631j_j4=h@r*b(*z-o4wt(vd^$%juenm5-a&f0&=sb3%_fl0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'drf_spectacular',
    'django_filters',
    'usuarios',
    'empleados',
    'recibos',
    'notificaciones',
    'horarios',
    'incidentes',
    'sanciones',
    'asistencias',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'api_nuevas_energias.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api_nuevas_energias.wsgi.application'



from urllib.parse import urlparse, parse_qsl
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASE_URL='postgresql://neondb_owner:npg_5r0DqiAEpGTI@ep-super-sound-addcues3-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'
tmpPostgres = urlparse(DATABASE_URL)

# conexion a bd postresql NEON(en la nube)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': tmpPostgres.path.replace('/', ''),
#         'USER': tmpPostgres.username,
#         'PASSWORD': tmpPostgres.password,
#         'HOST': tmpPostgres.hostname,
#         'PORT': 5432,
#         'OPTIONS': dict(parse_qsl(tmpPostgres.query)),
#         'CONN_MAX_AGE': 600,
#     }
# }

# CONEXION A BD MYSQL(cada uno debe completar con sus correspondientes datos)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'nuevas-energias-db',
        'USER': 'root',
        'PASSWORD': 'sasa',
        'HOST': 'localhost',
        'PORT': 3306
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Cambia 'UTC' por la zona horaria de tu país/región.
# Esto es CRUCIAL para que los cálculos de retraso y las validaciones de horario funcionen correctamente.
# Ejemplo para Argentina: 'America/Argentina/Buenos_Aires'
TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# --- CONFIGURACIÓN DE DJANGO REST FRAMEWORK ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Reemplaza la autenticación por defecto con la nuestra
        'usuarios.authentication.ExpiringTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # Asegúrate de que las vistas requieran autenticación por defecto si lo necesitas
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- TIEMPO DE VIDA DEL TOKEN ---
# Puedes ajustar este valor según tus necesidades
TOKEN_LIFETIME = timedelta(hours=12) # Ejemplo: 12 horas

# --- TIEMPO DE VIDA DEL TOKEN DE RESETEO DE CONTRASEÑA ---
# Define el tiempo en segundos que un enlace de reseteo de contraseña es válido.
# 86400 segundos = 24 horas = 1 día.
PASSWORD_RESET_TIMEOUT = 86400

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- CONFIGURACIÓN DE DRF-SPECTACULAR (SWAGGER) ---
SPECTACULAR_SETTINGS = {
    'TITLE': 'API Nuevas Energías',
    'DESCRIPTION': 'Documentación de la API para el proyecto de gestión de Nuevas Energías.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False, # No incluir el schema en la UI, se sirve por separado
}

# --- CONFIGURACIÓN DE LOGGING ---
# Esta configuración hará que los mensajes de nivel INFO y superior
# se muestren en la consola durante el desarrollo.
LOGGING = {
    'version': 1,
    # Es importante no deshabilitar los loggers existentes de Django.
    'disable_existing_loggers': False,
    # Define el formato de los mensajes.
    'formatters': {
        'simple': {
            'format': '[{asctime}] {levelname} {module} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    # Define a dónde se enviarán los logs (en este caso, a la consola).
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    # Configuración para el logger raíz, que captura todos los logs.
    'root': {
        'handlers': ['console'],
        'level': 'INFO',  # Nivel mínimo a registrar. Cambia a 'DEBUG' si necesitas más detalle.
    },
}

# --- Configuración de Email para Gmail ---
# ADVERTENCIA DE SEGURIDAD: No guardes tus credenciales en el control de versiones (Git).
# Rellena estas variables localmente para probar el envío de correos.
# Para Gmail, DEBES usar una "Contraseña de aplicación" generada desde tu cuenta de Google.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'maximiliano.guaymas480@gmail.com'  # TU CORREO DE GMAIL AQUÍ (ej: 'tu.correo@gmail.com')
EMAIL_HOST_PASSWORD = 'akazpckjgnuvangp'  # TU CONTRASEÑA DE APLICACIÓN DE 16 CARACTERES AQUÍ

# El remitente debe ser el mismo que el usuario para que Gmail funcione
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Si las credenciales no están configuradas, usa la consola para no fallar en desarrollo.
if DEBUG and not EMAIL_HOST_PASSWORD:
    print("ADVERTENCIA: Credenciales de correo no configuradas. Usando backend de consola.")
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# --- CONFIGURACIÓN DE CACHÉ ---
# Para desarrollo, usamos el backend de caché en memoria (LocMemCache).
# Es rápido y no requiere configuración externa.
# Para un entorno de producción, se recomienda cambiar a un backend más robusto
# como Redis (django-redis) o Memcached (django-pylibmc).
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',  # Un nombre único para este caché en memoria
    }
}
