# Generated by Django 5.2.6 on 2025-11-02 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('incidentes', '0003_alter_resolucion_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SancionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sancion', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('id_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones_empleado', to='empleados.empleado')),
                ('id_sancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanciones.sancion')),
                ('incidente_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanciones', to='incidentes.incidenteempleado')),
                ('responsable', models.ForeignKey(blank=True, help_text='Empleado que registra la sanción.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanciones_creadas', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Sanción de Empleado',
                'verbose_name_plural': 'Sanciones de Empleados',
            },
        ),
    ]
