# Generated by Django 5.2.6 on 2025-10-30 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('lunes', models.BooleanField(default=True)),
                ('martes', models.BooleanField(default=True)),
                ('miercoles', models.BooleanField(default=True)),
                ('jueves', models.BooleanField(default=True)),
                ('viernes', models.BooleanField(default=True)),
                ('sabado', models.BooleanField(default=False)),
                ('domingo', models.BooleanField(default=False)),
                ('cantidad_personal_requerida', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Personal Requerida')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_horario', to='empleados.empleado')),
                ('id_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='horarios.horarios')),
            ],
        ),
    ]
