# Generated by Django 5.2.6 on 2025-11-25 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='id_asignacion_horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horarios.asignacionhorario'),
        ),
    ]
